const I18N = {
  en: {
    eyebrow:"HALLOWEEN SOCIAL DECEPTION DANCE GAME",
    tagline:"Dance. Deceive. Survive.",
    heroText:"You can see everyone’s Curse — except your own. Dance when the music plays. Freeze when it stops. Trick the others before they trick you.",
    musicOn:"Music ON = Dance",
    musicOff:"Music OFF = Freeze",
    oneMistake:"One clear mistake = OUT",
    roundLength:"Up to 10 min / round",
    learnRules:"LEARN THE RULES ↓",
    goPublicPage:"GO TO THE FINAL BELL PAGE ↗",
    yourView:"WHAT YOU SEE",
    you:"YOU",
    demoCopy:"Everyone can read the Curse above your head. You cannot.",
    howEyebrow:"HOW TO PLAY",
    howTitle:"Four rules. Plenty of betrayal.",
    step1Title:"Wear your Curse",
    step1Text:"A random Curse Card is placed above your head. Everyone can see it except you.",
    step2Title:"Dance & deceive",
    step2Text:"When music plays, keep moving. Bluff, bait, imitate and mislead the other Zombies.",
    step3Title:"Freeze",
    step3Text:"When the music stops, freeze immediately. Clear movement after the stop can eliminate you.",
    step4Title:"Avoid your own Curse",
    step4Text:"Perform your own forbidden move and you are out. Each round lasts up to 10 minutes; if multiple Zombies remain, a Final Challenge decides the winner.",
    mindEyebrow:"THE MIND GAME",
    mindTitle:"Make them do it.",
    mindText:"You are allowed to talk, bluff and tell another player to perform a move. They choose whether to trust you.",
    mindHighlight:"Social “ganging up” is allowed. Physical surrounding, blocking or touching is not.",
    alwaysEyebrow:"REMEMBER",
    alwaysTitle:"Your Curse is always active.",
    alwaysText:"Even while calling out another player, your own Curse still applies. Point at someone while your Curse is POINT? You may eliminate yourself.",
    doubleTrouble:"DOUBLE TROUBLE IS POSSIBLE.",
    callEyebrow:"CALL-OUT SYSTEM",
    callTitle:"Saw a Curse happen? Call it.",
    call1:"DANCE", call1Sub:"Music playing",
    call2:"FREEZE", call2Sub:"Music stops",
    call3Sub:"Players may call out a clear violation",
    call4:"HELPER CHECK", call4Sub:"Helpers make the final decision",
    callNote:"A call-out requests a check — it does not automatically eliminate someone. If the violation is unclear, the player stays. Helper decision is final.",
    curseEyebrow:"CURSE DATABASE",
    curseTitle:"Classified. Mostly.",
    curseIntro:"There are many possible Curses, and some may repeat. You will not know the full card pool. Here are only a few examples:",
    curseSecret:"Full Curse pool hidden. Repeated Curses are possible.",
    rulesEyebrow:"QUICK RULES",
    rulesTitle:"Chaos, with boundaries.",
    rule1:"Talking, bluffing, baiting and misleading are allowed.",
    rule2:"You may ask another player to perform an action.",
    rule3:"Players may cooperate or socially target one player.",
    rule4:"Do not directly read or reveal another player’s Curse Card.",
    rule5:"No physical contact, pushing, grabbing, blocking or cornering.",
    flexEyebrow:"FLEXIBLE GROUP PLAY",
    flexTitle:"More Zombies. More chaos.",
    flexText:"Group size is flexible. Rounds can start when enough Zombies gather, or a larger group can play together after The Final Bell. If the crowd gets large, helpers may divide the floor into judging zones while everyone uses the same music.",
    included:"Included with The Final Bell ticket",
    walkinStart:"Public walk-in access: Start from 9pm (Free)",
    venueTba:"Zombie Dance venue: ROOM 302",
    openEyebrow:"OPEN SESSION", openTitle:"Everyone can join at the end.", openText:"For the final 30 minutes of the event, Zombie Dance opens to everyone for free. No prizes — just one last round of chaos before closing.", openBadge:"FREE PLAY · NO PRIZES",
    helpEyebrow:"NEED HELP?",
    helpTitle:"Questions?",
    helpText:"If you have any questions about Zombie Dance or The Final Bell, feel free to contact me.",
    waHint:"Chat with me on WhatsApp",
    igHint:"View updates on Instagram",
    publicTitle:"The Final Bell",
    publicHint:"Open the main event page",
    organisedBy:"Organised by:",
    footerTag:"Dance. Deceive. Survive."
  },
  zh: {
    eyebrow:"万圣节 · 社交智斗舞蹈游戏",
    tagline:"跳舞。欺骗。活下来。",
    heroText:"你看得到所有人的 Curse，唯独看不到自己的。音乐响就动，音乐停就 Freeze。在别人骗到你之前，先骗他们。",
    musicOn:"音乐响 = 跳舞",
    musicOff:"音乐停 = Freeze",
    oneMistake:"明显犯规一次 = OUT",
    roundLength:"每轮最多 10 分钟",
    learnRules:"查看规则 ↓",
    goPublicPage:"前往 The Final Bell 主页面 ↗",
    yourView:"你看到的画面",
    you:"你",
    demoCopy:"所有人都看得到你头上的 Curse，只有你自己看不到。",
    howEyebrow:"怎么玩",
    howTitle:"四条规则，很多背叛。",
    step1Title:"戴上你的 Curse",
    step1Text:"随机一张 Curse Card 会放在你的头上。其他人都看得到，只有你自己看不到。",
    step2Title:"跳舞 & 欺骗",
    step2Text:"音乐响时必须持续移动。你可以 bluff、诱导、模仿、误导其他 Zombie。",
    step3Title:"Freeze",
    step3Text:"音乐一停必须立即定格。停下后仍有明显动作，可能直接被淘汰。",
    step4Title:"别踩中自己的 Curse",
    step4Text:"做出自己头上的禁忌动作就 OUT。每轮最多 10 分钟；如果时间到还有多于一位 Zombie，就进入 Final Challenge 决胜。",
    mindEyebrow:"心理战",
    mindTitle:"让他们自己踩雷。",
    mindText:"你可以讲话、骗人，也可以直接叫其他玩家做某个动作。要不要相信你，是他们自己的选择。",
    mindHighlight:"允许社交上的“围攻”和集体诱导；不允许真的围住、挡住或触碰别人。",
    alwaysEyebrow:"记住",
    alwaysTitle:"你的 Curse 永远生效。",
    alwaysText:"就算你在举报别人，你自己的 Curse 仍然有效。如果你的 Curse 是 POINT，却激动地指着别人，你也可能把自己送走。",
    doubleTrouble:"双杀是可能发生的。",
    callEyebrow:"CALL-OUT 判定",
    callTitle:"看到有人踩中 Curse？喊出来。",
    call1:"DANCE", call1Sub:"音乐播放中",
    call2:"FREEZE", call2Sub:"音乐停止",
    call3Sub:"玩家可以举报明显犯规",
    call4:"HELPER CHECK", call4Sub:"最终由 Helper 判定",
    callNote:"Call-out 只是要求 Helper 检查，不代表自动淘汰。情况不明确时，玩家继续留场。Helper 判定为最终决定。",
    curseEyebrow:"CURSE DATABASE",
    curseTitle:"机密。大概吧。",
    curseIntro:"Curse 有很多种，而且可能重复。完整卡池不会公开。这里只给你看几个例子：",
    curseSecret:"完整 Curse 卡池保密；重复 Curse 完全有可能。",
    rulesEyebrow:"快速规则",
    rulesTitle:"可以乱，但有边界。",
    rule1:"可以讲话、bluff、bait、误导别人。",
    rule2:"可以直接叫其他玩家做某个动作。",
    rule3:"可以合作，也可以一起在心理上针对某一位玩家。",
    rule4:"不可以直接读出或公开别人头上的 Curse Card。",
    rule5:"禁止推、抓、挡路、把人围住或其他身体接触。",
    flexEyebrow:"人数 FLEXIBLE",
    flexTitle:"Zombie 越多，越乱。",
    flexText:"人数不固定。够人就可以开一轮，也可以等 The Final Bell 一轮结束后让更多人一起玩。人数太多时，Helpers 可以把场地分成不同判定区，但大家仍使用同一首音乐。",
    included:"The Final Bell 门票已包含",
    walkinStart:"Public walk-in access：9PM 起免费开放",
    venueTba:"Zombie Dance 场地：ROOM 302",
    openEyebrow:"OPEN SESSION", openTitle:"最后大家都可以加入。", openText:"活动最后 30 分钟，Zombie Dance 会免费开放给所有人。",
    helpEyebrow:"有问题吗？",
    helpTitle:"Questions?",
    helpText:"如果你对 Zombie Dance 或 The Final Bell 有任何问题，可以直接联系我。",
    waHint:"通过 WhatsApp 找我",
    igHint:"到 Instagram 看更新",
    publicTitle:"The Final Bell",
    publicHint:"打开主活动页面",
    organisedBy:"主办：",
    footerTag:"跳舞。欺骗。活下来。"
  }
};

let lang = localStorage.getItem("zombie_dance_lang") || "en";
function applyLanguage(){
  if(!I18N[lang]) lang = "en";
  document.documentElement.lang = lang === "zh" ? "zh-CN" : "en";
  document.querySelectorAll("[data-i18n]").forEach(el => {
    const key = el.dataset.i18n;
    if (I18N[lang] && I18N[lang][key] != null) el.textContent = I18N[lang][key];
  });
  document.querySelectorAll(".lang-btn").forEach(btn => btn.classList.toggle("active", btn.dataset.lang === lang));
  localStorage.setItem("zombie_dance_lang", lang);
}
document.querySelectorAll(".lang-btn").forEach(btn => btn.addEventListener("click",()=>{lang=btn.dataset.lang;applyLanguage();}));
applyLanguage();
